#! /bin/sh

cc -std=c99 -pedantic -Wall -o program bag_console.c test.c ../text/bag_text.c ../engine/x11/bag_x11.c ../engine/glad/src/gl.c -I./ -I../text/ -I../engine/ -I../engine/glad/include -lGL -lX11 -lXi -ldl -lm
